### ISSUE TITLE
Order of Traversal for Beginners

### ISSUE THREAD

**Issue by ordaz00** [SkalskiP/courses#36]
First of all thank you so much for creating this repo, I would like to suggest that you create a small roadmap that people can follow so that they know a rough order to view them in.

**Comment by SkalskiP** [comment]
Hi @ordaz00 👋🏻! I already started to work on that. You can read more [here](https://github.com/SkalskiP/courses/discussions/20).

**Comment by ordaz00** [comment]
That looks great keep up the great work.
